### PR TITLE
add v2 config psr-4 autoload in composer.json

### PR DESCRIPTION
**Pull request by yutakachiba**
An error occured after composer update.

PHP Fatal error: Uncaught exception 'ReflectionException' with message 'Class Aura\Marshal_Config\Common does not exist'

So add autoload psr-4 config.

(PR again. As I checkout "master" not "develop")

### CODE REVIEW

**Comment by harikt** [comment]
Thank you @chobe3x .

And thanks for sending the PR again. Sorry for the hassale.

**Comment by harikt** [comment]
You can see the earlier PR `files changed` tab, and the current one to feel the difference .

**Comment by yutakachiba** [comment]
Thank you @harikt .

I see the difference of two PRs. Sorry for wrong checkout.

And again thank you for your help. Anyway I can send my first PR : )

**Comment by harikt** [comment]
No problem :) .

Happy to help.

After a few days you can see here http://auraphp.com/contributors/

**Pull request merged**
