### PR TITLE
Type/Builder: allow to have custom generic type class.

### PR DESCRIPTION
**Pull request by sobstel**
It's possible to have custom GenericEntity class, but it's not possible to have the same with GenericType. This pull request changes it.

### CODE REVIEW

**Comment by harikt** [comment]
@pmjones will look into this. I don't know what is the purpose of doing this.

**Comment by sobstel** [comment]
I'm developing library where I want to extend GenericType functionality. At this moment I need to overwrite and copy/paste whole Aura\Marshal\Type\Builder::newInstance() just to replace `new GenericType` with `new My\Own\GenericType`.

All other Aura.Marshal builders allow custom classes (except Collection, but it's not big problem there as there's just `new GenericCollection($data)`), so it's also not consistent.

**Comment by harikt** [comment]
ok thanks. @pmjones will look into this and merge. 

Paul for your reference the project is https://github.com/sobstel/agnostic .

**Comment by sobstel** [comment]
This project is under heavy development (or rather experimentation), but see how ugly way I needed to work around it: https://github.com/sobstel/agnostic/blob/master/src/Type/Builder.php#L24

**Comment by harikt** [comment]
@pmjones could you have a look into this ?

**Pull request merged**
