### PR TITLE
Allow using plain PHP objects without traits or magic super-class.

### LINKED ISSUE #25: Allow protected/private properties without magic method
Currently https://github.com/auraphp/Aura.Marshal/blob/1.x/src/Aura/Marshal/Entity/Builder.php#L49 forces you to have public properties or using one of the provided traits which define `__set` magic method.

To allow having entities without this magic, I'd recommend to improve the Entity\Builder a bit to write into private/protected properties directly using a class bound setter function.

So instead of doing

``` php
foreach ($data as $field => $value) {
     $entity->$field = $value;
}
```

we could do

``` php
$writer = \Closure::bind(
    function ($object, $prop, $value) {
        $object->$prop = $value;
    },
    null,
    get_class($entity)
);

foreach ($data as $field => $value) {
     $writer($entity, $field, $value);
}
```

@pminnieur

### PR DESCRIPTION
**Pull request by marcj**
Removed the need of the magic traits.
Fixed some CS/unused imports.

This approach is now using a proxy like in Doctrine/Propel2 to lazy load relations/properties.

Fixes #25.

### CODE REVIEW

**Comment by pmjones** [comment]
First, I like the idea of being able to load up the properties the way you describe.

Unfortunately, this PR has some major BC breaks, such as the removal of GenericEntity and the "magic" traits. Current users depend on them being present, along with the functionality they provide as they are. We can't have BC breaks in a stable 1.x release, so the PR as currently submitted is a no-go.

Having said that, is there some way to add the functionality you've described, without removing the previously-existing functionality? My guess is that it might involve checking the entity to see if it implements those traits, using them if they exist, and using your alternate if they do not. That might look dirtier than you'd like, but it would not break BC.

**Comment by marcj** [comment]
Well, I'm not in the position to say in which version this should go. I know that this break BC by removing those classes, but nothing is wrong if you decide to release v2.0. :P 

However, if you want to have this in v1.x then I'm going to find a way to support both.

**Comment by marcj** [comment]
Backward compatibility restored, pushed and green.

**Comment by marcj** [comment]
Just improved code coverage to 100%. Also, I removed `RelationInterface::getForeignType` as it was never in use in the actual code. Is this method used in previous versions?

**Comment by pmjones** [comment]
Dude I appreciate the full coverage. Very nice.

Regarding getForeignType(), let's not remove things, even if they appear unused. The smallest number of changes is best. ;-)

Some further picks:
- I see `use Aura\Marshal\Lazy\BuilderInterface as LazyBuilderInterface` became `use Aura\Marshal\Lazy\LazyInterface`. What's that about?
- I also see `protected $class = 'Aura\Marshal\Entity\GenericEntity'` became `stdClass`. That means the default class being returned is now stdClass, which is a BC break; users may be depending on that type for some reason.
- The whitespace changes in `Aura/Marshal/Type/Builder.php` add noise to that diff. I get that some folks don't prefer to collapse the `!` into the following element, along with the spaces-for-aligment stuff, but "fewer changes is better" in this case (especially insubstantial ones). My bet is that your IDE applied some automatic corrections.
- Finally, and this might be kind of a big deal: `eval()`? Is there any way at all to avoid that?

Thanks for your patience with this review.

**Comment by marcj** [comment]
> I see use Aura\Marshal\Lazy\BuilderInterface as LazyBuilderInterface became use Aura\Marshal\Lazy\LazyInterface. What's that about?

That interface was never in use in that class, but `LazyInterface` is now used.

> I also see protected $class = 'Aura\Marshal\Entity\GenericEntity' became stdClass.

fixed

> noise

fixed

> Finally, and this might be kind of a big deal: eval()?

PHP doesn't allow us to dynamically define classes. Since we need a proxy class to emulate lazy loading, there's no way around eval. Alternative could be to write the code down to the file system and `include` it, but there's no win with that approach (except performance for opcode cacher, but that's marginal).

**Comment by marcj** [comment]
I also added RelationInterface::getForeignType back, which decreases code coverage since its never in use.

**Comment by marcj** [comment]
@pmjones any news here? I would like to finish this as we need it in our project. :)

**Comment by marcj** [comment]
@pmjones ping

**Comment by pmjones** [comment]
Sorry, been busy with other projects. Will look at this again today/tomorrow. Thanks for your patience.

**Comment by marcj** [comment]
ping @pmjones

**Pull request closed without merging**
