### PR TITLE
Added Functionality to delete Entities

### PR DESCRIPTION
**Pull request by mapthegod**
### deleteEntity()

Added 

``` php
Aura\Marshal\Type\GenericType->deleteEntity($identity_value)
```

The Function takes the identity_value of the Entity to be deleted as parameter and deletes it from all indicies.
### getDeletedEntitiesIds()

Added

``` php
Aura\Marshal\Type\GenericType->getDeletedEntitiesIds()
```

The function takes no arguments and returns an array of identity_values of Entities deleted using deleteEntity()
### Tests

Added several test for the Deletion Functionality

### CODE REVIEW

**Comment by harikt** [comment]
May I know why you need delete Entities?

**Comment by mapthegod** [comment]
@harikt I'm working on a DataProvider which automatically handles saving new, updated and now also deleted Entities to a backend. And as I need to have a delete functionality on some of the Entites, I wrote these little functions.
I just decided to open a pull request to share it with you, and discuss whether it should be merged into the main repo or not.

**Comment by mapthegod** [comment]
We may also discuss this in the IRC, if you wish

**Comment by harikt** [comment]
@mapthegod Thank you for the quick response. I was just curious to know, that's all. Please wait for @pmjones to look into it further . I am not that much into Marshal :) .

**Pull request merged**
